api:
  dashboard: true # Optional can be disabled
  insecure: false # Optional can be disabled
  debug: false # Optional can be Enabled if needed for troubleshooting

entryPoints:
  insecure:
    address: ":80"
    # Optional if you want to redirect all HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: web
          scheme: https
  web:
    address: ":443"

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    watch: true
    network: web # Optional; Only use the "proxy" Docker network, even if containers are on multiple networks.

  file:
    filename: "dynamic.toml"

certificatesResolvers:
  lets-encrypt:
    acme:
      email: youremail@email.com
      storage: /certs/acme.json
      # caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      tlsChallenge: true